server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: lldj123414

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 763450589094-8latjin0q361qo5auts8i34lscgrku5m.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 1357867378234638
            client-secret: 7f68509c4fecb1c6f1e08334374469aa
            scope:
              - email
              # 페이스북이 제공하는 프로파일 이름을 정확히 적어야함
              - public_profile

          naver:
            client-id: yBb_FKhW72KRSgBk9iVR
            client-secret: b4O96dyAtO
            scope:
              - email
              - name
              #- profile_image - 네이버는 profile_image라는 것도 존재함
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver #구글, facebook은 원래 설정이 되어있어서 안적어줘도되지만 naver은 적어줘야한다.

        provider:
          # 네이버는 공식 provider로 등록이 안되어 있어서 등록을 해줘야함
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 창
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보
            user-name-attribute: response # 회원 정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줌
